### ISSUE TITLE
Installation fail on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by bydooweedoo** [leveros/leveros#22]
Hello,

I am currently using ubuntu 14.04 LTS and follow installation instructions.

After cloning the repository and try `make`, it fails with the following error:

``` shell
make HAVE_GO="" HAVE_PROTOC="" clicommon
make[1]: Entering directory `/path/leveros'
if [ -n "" ]; then protoc -I protos/core/ --go_out=plugins=grpc:core/ protos/core/leverrpc.proto ; else echo "Warning! protoc not found." "Should be ok if not modifying protos." ; fi
Warning! protoc not found. Should be ok if not modifying protos.
if [ -n "" ]; then protoc -I protos/fleettracker/ --go_out=plugins=grpc:fleettracker/ protos/fleettracker/fleettracker.proto ; else echo "Warning! protoc not found." "Should be ok if not modifying protos." ; fi
Warning! protoc not found. Should be ok if not modifying protos.
if [ -n "" ]; then protoc -I protos/hostman/ --go_out=plugins=grpc:hostman/ protos/hostman/manager.proto ; else echo "Warning! protoc not found." "Should be ok if not modifying protos." ; fi
Warning! protoc not found. Should be ok if not modifying protos.
if [ -n "" ]; then make GO_OUTPUT=build/bin/lever GO_MAIN_TARGET=./cmd/lever/main.go build/bin/lever ; else test -f build/bin/lever || docker run --rm -v "/path/leveros":/go/src/github.com/leveros/leveros -w /go/src/github.com/leveros/leveros -e GOOS=linux -e GOARCH=amd64 -e CGO_ENABLED=0 golang:1.6.1-alpine go build -ldflags "-X main.Version=0.1.0 -X main.GitHash=fd973d2817b0efcee368c08d8a08dc2c8d833fbd"  -o build/bin/lever ./cmd/lever/main.go ; fi
stat ./cmd/lever/main.go: no such file or directory
make[1]: *** [build/bin/lever] Error 1
make[1]: Leaving directory `/path/leveros'
```

I changed my real path with `/path/leveros` which point to the cloned repository.

Docker version:

``` shell
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

Docker machine:

``` shell
$ docker-machine version
docker-machine version 0.7.0, build a650a40
```

Docker compose:

``` shell
$ docker-compose version
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

Virtual box:

``` shell
$ apt show virtualbox-5.0
Package: virtualbox-5.0
Version: 5.0.20-106931~Ubuntu~trusty
```

Protoc:

``` shell
$ protoc --version
libprotoc 2.6.1
```

Thank you for your help,
I really can't wait to test leveros :) !

**Comment by vladaionescu** [comment]
Hi there,

Not sure what you mean by "I changed my real path with /path/leveros which point to the cloned repository." Is `/path/leveros` a symlink to the git-cloned leveros?

I have very similar setup in terms of versions - though I don't use docker-machine+VirtualBox in linux. Should work fine via native Docker.

Might be easier to debug this together over [Gitter](https://gitter.im/vlad-alexandru-ionescu).

**Comment by bydooweedoo** [comment]
Hi,

For the path it is not a symlink, I just mean `/path/leveros` is just the path I put for the purpose of this issue. In my computer, this path is different but it is not really important sorry about that ^^'.

I will try Gitter thanks :)

**Comment by vladaionescu** [comment]
The issue was somehow related to using docker-machine on Ubuntu. Running with native docker worked fine. Closing this for now.

**Comment by bydooweedoo** [comment]
Hi there,

Just to let people knows how @vlad-alexandru-ionescu fixed this issue ;)

Just avoid using `docker-machine` use native docker directly.

To do so open a new terminal and try use `sudo` for every `make` command.

A cleaner way would be to add your current user to the same group the `docker` process is running under.

Thanks @vlad-alexandru-ionescu !!
