### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by heitorsilva** [leveros/leveros#26]
Hello guys!

I'm evaluating LeverOS for something we need at the company I work at, and we're concerned to see that there's almost 4 months that the project has no updates on Github.
The core guys are still active? The project will still be updated and maintained?

cc: @vlad-alexandru-ionescu, @bydooweedoo, @chetbox

**Comment by vladaionescu** [comment]
Hi there, we've taken a break from development. We'll provide an official update soon.
